"""Write docs/card_spec.md: every card's rules text plus its raw Lua effect names.

The effect names are the game's own C# function names. They disambiguate wording that
the printed text leaves vague -- ``RemoveOpponentInfluenceInWesternEuropeMax2`` pins
down both the region and the per-country cap -- so they are the authoritative spec for
each event implementation.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from twilight import events  # noqa: E402
from twilight.data import CARDS  # noqa: E402
from twilight.enums import Stage  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "docs" / "card_spec.md"


def effect_lines(spec: dict, indent: int = 0) -> list[str]:
    """Flatten the nested Lua effect declarations into readable lines."""
    lines: list[str] = []
    pad = "  " * indent

    def walk(node, depth: int) -> None:
        pad = "  " * depth
        if isinstance(node, list):
            # A leaf effect is ["FunctionName", data].
            if node and isinstance(node[0], str) and all(
                not isinstance(x, (list, dict)) for x in node[1:]
            ):
                data = node[1] if len(node) > 1 else 0
                extra = ""
                if isinstance(data, int) and data > 255:
                    # Several cards pack two numbers into one argument.
                    extra = f"   (packed: low={data & 0xFF}, high={data >> 8})"
                lines.append(f"{pad}- `{node[0]}`({data}){extra}")
                return
            for item in node:
                walk(item, depth)
        elif isinstance(node, dict):
            for key, value in node.items():
                lines.append(f"{pad}- **{key}**:")
                walk(value, depth + 1)

    for field, value in spec.items():
        lines.append(f"{pad}- **{field}**:")
        walk(value, indent + 1)
    return lines


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    implemented = set(events.EVENTS)
    out: list[str] = [
        "# Card specification",
        "",
        "Generated by `tools/dump_card_spec.py` from the game's own Lua database.",
        "Do not edit by hand.",
        "",
        "`effect_spec` entries are the game's internal C# effect-function names, which",
        "resolve ambiguities in the printed card text (regions, per-country caps, and",
        "which side acts). Treat them as the specification.",
        "",
    ]

    for stage in (Stage.EARLY_WAR, Stage.MID_WAR, Stage.LATE_WAR):
        in_stage = sorted(
            (c for c in CARDS.values() if c.stage is stage), key=lambda c: c.number
        )
        out.append(f"## {stage.value}")
        out.append("")
        for c in in_stage:
            flags = []
            if c.optional:
                flags.append("OPTIONAL")
            if c.remove_on_event:
                flags.append("remove-on-event (*)")
            if not c.may_be_held:
                flags.append("must be played")
            if not c.can_headline:
                flags.append("cannot headline")
            if c.is_scoring:
                flags.append(f"scoring: {c.scoring_region}")
            status = "IMPLEMENTED" if c.name in implemented else "TODO"

            side = c.side.label if c.side is not None else "Neutral"
            out.append(f"### #{c.number} {c.name}  [{status}]")
            out.append("")
            out.append(f"- side: **{side}**, ops: **{c.ops}**, stage: {stage.value}")
            if flags:
                out.append(f"- flags: {', '.join(flags)}")
            out.append("- text:")
            out.append("")
            for line in c.event_text.split("\n"):
                out.append(f"  > {line}")
            out.append("")
            if c.effect_spec:
                out.append("- effect_spec:")
                out.append("")
                out.extend("  " + line for line in effect_lines(c.effect_spec))
                out.append("")

    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    todo = [c for c in CARDS.values() if c.name not in implemented]
    print(f"wrote {OUT} ({len(CARDS)} cards, {len(todo)} still TODO)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
